export default [
  {
    name: 'Stanislav',
    surname: 'Yurchenko',
    photo: '../images/team/yurchenko.jpg',
    position: ['Team Leader', 'Frontend Developer'],
    githubLink: 'https://github.com/StanislavYurchenko',
  },
  {
    name: 'Yulia',
    surname: 'Labutkina',
    photo: '../images/team/labutkina.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/YuliaLabutkina',
  },
  {
    name: 'Artur',
    surname: 'Stahov',
    photo: '../images/team/stahov.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/ArturStahov',
  },
  {
    name: 'Inna',
    surname: 'Tishchenko',
    photo: '../images/team/tishchenko.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/inna91',
  },
  {
    name: 'Andriy',
    surname: 'Krichkivskiy',
    photo: '../images/team/krichkivskiy.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/Andriy1982',
  },
  {
    name: 'Volodymyr',
    surname: 'Babych',
    photo: '../images/team/babych.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/vovababych',
  },
  {
    name: 'Kyrylo',
    surname: 'Hrebin',
    photo: '../images/team/hrebin.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/kyrylohrebin',
  },
  {
    name: 'Ihor',
    surname: 'Levchenko',
    photo: '../images/team/levchenko.jpg',
    position: ['Frontend Developer'],
    githubLink: 'https://github.com/IhorLev1',
  },
];
